pages:
  image: node:12.17.0
  script:
    - npm install -g @dendronhq/dendron-cli @dendronhq/dendron-11ty
    - dendron buildSite --stage prod
    - mv docs public
  artifacts:
    paths:
      - public
