pages:
  image: node:12.17.0
  script:
    - yarn
    - npx dendron buildSite --wsRoot . --stage prod --vault vault
    - mv docs public
  artifacts:
    paths:
      - public

  script:
    - yarn
    - npx dendron buildSite --wsRoot . --stage prod
    - mv docs public
  artifacts:
    paths:
      - public
