cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .next/cache/

pages:
  image: node:14
  script:
    - npm install
    - npm install -g @dendronhq/dendron-cli
    - (test -d .next) && (echo 'updating dendron next...' && cd .next && git reset --hard && git clean -f && git pull) || (echo 'init dendron next' && npx dendron publish init)
    - cd .next && npm install && cd ..
    - npx dendron publish build
    - cd .next && yarn export && cd ..
    - (test -d docs && rm -rf docs) || echo skipping
    - cd .next && mv out ../public
  artifacts:
    paths:
      - public
